name: flavored_app_demo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  http: ^0.13.5
  get: ^4.6.5
  talker: ^2.0.0+1
  built_value: ^8.4.2
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/
